### ISSUE TITLE
Suggestion instead of --bind-mount

### ISSUE THREAD

**Issue by thenktor** [oxplot/rsyncbtrfs#14]
Hi,

from your description: 
> You can use --bind-mount argument when backing up to instruct rsyncbtrfs to bind mount the source directory under a temp path. This is useful when you don't want to backup all the mount points under the source:

Why not just use the rsync option:
> -x, --one-file-system       don't cross filesystem boundaries

Basically I think this does the same with less overhead.

**Comment by oxplot** [comment]
It's not the same thing. It's perfectly OK to mount a volume on top of a directory that has content in it which will hide that content until unmounted. Using rsync's `-x`, the hidden content is simply ignored. With bind mount, the hidden content is also backed up.

**Comment by thenktor** [comment]
Yes, you are right :+1: That's a perfectly valid point for the /dev dir. Maybe you can add the info to the readme.

**Comment by oxplot** [comment]
Done.
